Improved pre-commit hook script

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,13 +1,22 @@
 bash << 'EOF'
+runTests() {
+    npm run test || { echo "Tests failed"; exit 1; }
+    npm run build-test || { echo "Build test failed"; exit 1; }
+}
+main(){
 branch_name=$(git branch --show-current)
 if [[ $branch_name = "main" ]] || [[ $branch_name = "prelease" ]]; then
-exit 1;
+  echo "Error: Linting and tests are not allowed on $branch_name branch."
+  exit 1;
 fi
-npm run lint
-npm run check-format
+npm run lint || { echo "Linting failed"; exit 1; }
+npm run check-format || { echo "Format check failed"; exit 1; }
 if [[ $branch_name = "development" ]]; then
-  npm run test run
-  npm run build-test
+  runTests
 fi
+}
+
+main
+
 EOF
 
